const countries = {
  Australia: "au",
  Brazil: "br",
  Canada: "ca",
  Switzerland: "ch",
  China: "cn",
  Germany: "de",
  Egypt: "eg",
  Spain: "es",
  France: "fr",
  "United Kingdom": "gb",
  Greece: "gr",
  "Hong Kong": "hk",
  Ireland: "ie",
  Israel: "il",
  India: "in",
  Italy: "it",
  Japan: "jp",
  Netherlands: "nl",
  Norway: "no",
  Peru: "pe",
  Philippines: "ph",
  Pakistan: "pk",
  Portugal: "pt",
  Romania: "ro",
  "Russian Federation": "ru",
  Sweden: "se",
  Singapore: "sg",
  "Taiwan, Province of China": "tw",
  "Ukraine	": "ua",
  "United States": "us",
};
