const languages = {
  Arabic: "ar",
  German: "de",
  Greek: "el",
  English: "en",
  Spanish: "es",
  French: "fr",
  Hebrew: "he",
  Hindi: "hi",
  Italian: "it",
  Japanese: "ja",
  Malayalam: "ml",
  Marathi: "mr",
  Dutch: "nl",
  Norwegian: "no",
  Portuguese: "pt",
  Romanian: "ro",
  Russian: "ru",
  Swedish: "sv",
  Tamil: "ta",
  Telugu: "te",
  Ukrainian: "uk",
  Chinese: "zh",
};
