const languages = {
  Arabic: "ar",
  German: "de",
  Greek: "el",
  English: "en",
  Spanish: "es",
  French: "fr",
  Hebrew: "he",
  Hindi: "hi",
  Italian: "it",
  Japanese: "ja",
  Malayalam: "ml",
  Marathi: "mr",
  Dutch: "nl",
  Norwegian: "no",
  Portuguese: "pt",
  Romanian: "ro",
  Russian: "ru",
  Swedish: "sv",
  Tamil: "ta",
  Telugu: "te",
  Ukrainian: "uk",
  Chinese: "zh",
};

const countries = {
  Australia: "au",
  Brazil: "br",
  Canada: "ca",
  Switzerland: "ch",
  China: "cn",
  Germany: "de",
  Egypt: "eg",
  Spain: "es",
  France: "fr",
  "United Kingdom": "gb",
  Greece: "gr",
  "Hong Kong": "hk",
  Ireland: "ie",
  Israel: "il",
  India: "in",
  Italy: "it",
  Japan: "jp",
  Netherlands: "nl",
  Norway: "no",
  Peru: "pe",
  Philippines: "ph",
  Pakistan: "pk",
  Portugal: "pt",
  Romania: "ro",
  "Russian Federation": "ru",
  Sweden: "se",
  Singapore: "sg",
  "Taiwan, Province of China": "tw",
  "Ukraine	": "ua",
  "United States": "us",
};

const topics = [
  "breaking-news",
  "world",
  "nation",
  "business",
  "technology",
  "entertainment",
  "sports",
  "science",
  "health",
];

export { languages, countries, topics };
